type: object
required:
  - name
  - cluster_id
  - template
properties:
  name:
    type: string
    description: The name of the service deployment
    example: "my-service"
  cluster_id:
    type: string
    format: uuid
    description: The unique identifier of the associated cluster
    example: "123e4567-e89b-12d3-a456-426614174000"
  template:
    $ref: '../schemas/service-template.yaml'
  namespace:
    type: string
    description: The namespace in which the service should be deployed in the target cluster
    example: "default"
  description:
    type: string
    description: The description of the service deployment
    example: "This is a Ray cluster service for distributed computing"
  to_be_deleted_at:
    type: string
    format: date-time
    description: The date and time the service deployment will be deleted
    example: "2025-02-01T00:00:00Z"